version: '3.8'

services:
  php:
    build: .
    ports:
      - "5555:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Vrieskist@247
      MYSQL_DATABASE: mbogodigital
      MYSQL_USER: mbogodigitalUser
      MYSQL_PASSWORD: Vrieskist@247
    volumes:
      - mysql_data:/var/lib/mysql

  # phpMyAdmin toevoeging
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: Vrieskist@247
    ports:
      - "8081:80"
    depends_on:
      - mysql

volumes:
  mysql_data: